# Generated by Django 3.0 on 2020-01-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код')),
                ('meta_title', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('meta_descr', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('meta_key', models.TextField(blank=True, null=True, verbose_name='Ключові слова')),
            ],
            options={
                'verbose_name': 'сторінкa',
                'verbose_name_plural': 'сторінки',
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Код, по якому картинка буде діставатися у хтмл-шаблоні', max_length=120, null=True, verbose_name='Код')),
                ('name', models.CharField(blank=True, help_text='Допоміжна описувальна назва', max_length=120, null=True, verbose_name='Назва')),
                ('value', models.ImageField(blank=True, help_text='Картинка, яка буде відображатися на сайті', null=True, upload_to='pages/', verbose_name='Картинка')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.Page', verbose_name='Сторінка')),
            ],
            options={
                'verbose_name': 'Картинки на сторінці',
                'verbose_name_plural': 'Картинки на сторінці',
                'unique_together': {('page', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PageFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Код, по якому контент буде діставатися у хтмл-шаблоні', max_length=120, verbose_name='Код')),
                ('name', models.CharField(blank=True, help_text='Допоміжна назва', max_length=120, null=True, verbose_name='Назва')),
                ('value', models.TextField(help_text='Контент, який буде відображатися на сайті', verbose_name='Текст')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.Page', verbose_name='Сторінка')),
            ],
            options={
                'verbose_name': 'текст сторінки',
                'verbose_name_plural': 'Текста сторінки',
                'unique_together': {('page', 'code')},
            },
        ),
    ]
