# Generated by Django 3.1 on 2020-08-15 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_document_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('format', models.CharField(blank=True, choices=[('STATUS1', 'STATUS1'), ('STATUS2', 'STATUS2'), ('STATUS3', 'STATUS3'), ('STATUS4', 'STATUS4')], default='STATUS1', max_length=255, null=True, verbose_name='Формат')),
                ('status', models.CharField(blank=True, choices=[('STATUS1', 'STATUS1'), ('STATUS2', 'STATUS2'), ('STATUS3', 'STATUS3'), ('STATUS4', 'STATUS4')], default='STATUS1', max_length=255, null=True, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_from', models.TimeField(verbose_name='Час від')),
                ('time_to', models.TimeField(verbose_name='Час до')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('mark', models.SmallIntegerField(blank=True, null=True, verbose_name='Оцінка')),
                ('advocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advocat_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Адвокат')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Консультація',
                'verbose_name_plural': 'Консультації',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Право',
            },
        ),
        migrations.CreateModel(
            name='ConsultationPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('consultation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.consultation', verbose_name='Консультація')),
            ],
            options={
                'verbose_name': 'Оплата до консультації',
                'verbose_name_plural': 'Оплати до консультацій',
            },
        ),
        migrations.CreateModel(
            name='ConsultationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.consultation', verbose_name='Консультація')),
            ],
            options={
                'verbose_name': 'Документ до консультації',
                'verbose_name_plural': 'Документи до консультацій',
            },
        ),
    ]
