# Generated by Django 3.0 on 2019-12-10 10:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191210_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='текст'),
        ),
    ]
