# Generated by Django 3.0.2 on 2020-01-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200129_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='post',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider',
            field=models.CharField(max_length=255, verbose_name='Номер слайдера'),
        ),
        migrations.AlterField(
            model_name='team',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='team',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Галузь'),
        ),
        migrations.AlterField(
            model_name='team',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='team',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефону2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Посилання на сайті'),
        ),
    ]
