# Generated by Django 3.0.2 on 2020-01-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200123_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Імя')),
                ('email', models.TextField(blank=True, null=True, verbose_name='Емайл')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Телефон')),
            ],
        ),
    ]
