# Generated by Django 3.1 on 2020-08-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_consultation_consultationdocument_consultationpayment_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='format',
            field=models.CharField(blank=True, choices=[('SKYPE', 'SKYPE'), ('VIBER', 'VIBER'), ('GMEET', 'GMEET'), ('ZOOM', 'ZOOM'), ('MOBILE', 'MOBILE')], default='SKYPE', max_length=255, null=True, verbose_name='Формат'),
        ),
    ]
