# Generated by Django 3.0 on 2019-12-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191210_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='phone2',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефону2'),
        ),
    ]
