# Generated by Django 3.0 on 2020-01-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_team_phone2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',), 'verbose_name': 'пост', 'verbose_name_plural': 'Блог'},
        ),
    ]
