# Generated by Django 3.1 on 2020-08-15 14:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефону')),
                ('role', models.CharField(choices=[('client', 'client'), ('advocat', 'advocat')], default='client', max_length=255, verbose_name='Роль')),
                ('rate', models.FloatField(verbose_name='Ціна за годину консультації')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt')),
            ],
            options={
                'verbose_name': 'клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('format', models.CharField(blank=True, choices=[('SKYPE', 'SKYPE'), ('VIBER', 'VIBER'), ('GMEET', 'GMEET'), ('ZOOM', 'ZOOM'), ('MOBILE', 'MOBILE')], default='SKYPE', max_length=255, null=True, verbose_name='Формат')),
                ('status', models.CharField(blank=True, choices=[('STATUS1', 'STATUS1'), ('STATUS2', 'STATUS2'), ('STATUS3', 'STATUS3'), ('STATUS4', 'STATUS4')], default='STATUS1', max_length=255, null=True, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('mark', models.SmallIntegerField(blank=True, null=True, verbose_name='Оцінка')),
                ('advocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advocat_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Адвокат')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Консультація',
                'verbose_name_plural': 'Консультації',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Імя')),
                ('email', models.TextField(blank=True, null=True, verbose_name='Емайл')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Право',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_descr', models.TextField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я")),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Галузь')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефону')),
                ('phone2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефону2')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Посилання на сайті')),
            ],
            options={
                'verbose_name': 'учасник',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.CharField(max_length=255, verbose_name='Номер слайдера')),
                ('clients', models.ManyToManyField(blank=True, null=True, related_name='sliders', to='gao.Client', verbose_name='Клієнти')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдери',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_descr', models.TextField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Посилання')),
                ('body', tinymce.models.HTMLField(blank=True, null=True, verbose_name='текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='зображення')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='gao.team')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документ',
            },
        ),
        migrations.CreateModel(
            name='ConsultationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField(verbose_name='Час від')),
                ('time_to', models.TimeField(verbose_name='Час до')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gao.consultation', verbose_name='Консультація')),
            ],
            options={
                'verbose_name': 'Година консультації',
                'verbose_name_plural': 'Години консультації',
            },
        ),
        migrations.CreateModel(
            name='ConsultationPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('consultation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gao.consultation', verbose_name='Консультація')),
            ],
            options={
                'verbose_name': 'Оплата до консультації',
                'verbose_name_plural': 'Оплати до консультацій',
            },
        ),
        migrations.CreateModel(
            name='ConsultationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gao.consultation', verbose_name='Консультація')),
            ],
            options={
                'verbose_name': 'Документ до консультації',
                'verbose_name_plural': 'Документи до консультацій',
            },
        ),
        migrations.AddField(
            model_name='projectuser',
            name='faculty',
            field=models.ManyToManyField(blank=True, to='gao.Faculty', verbose_name='Галузі права'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
