# Generated by Django 3.1 on 2020-08-15 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friday',
            field=models.BooleanField(default=True, verbose_name='Пятниця робочий день?'),
        ),
        migrations.AddField(
            model_name='user',
            name='friday_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Початок робочого дня в пятницю'),
        ),
        migrations.AddField(
            model_name='user',
            name='friday_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Закінчення робочого дня в пятницю'),
        ),
        migrations.AddField(
            model_name='user',
            name='monday',
            field=models.BooleanField(default=True, verbose_name='Понеділок робочий день?'),
        ),
        migrations.AddField(
            model_name='user',
            name='monday_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Початок робочого дня в понеділок'),
        ),
        migrations.AddField(
            model_name='user',
            name='monday_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Закінчення робочого дня в понеділок'),
        ),
        migrations.AddField(
            model_name='user',
            name='saturday',
            field=models.BooleanField(default=False, verbose_name='Субота робочий день?'),
        ),
        migrations.AddField(
            model_name='user',
            name='saturday_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Початок робочого дня в субботу'),
        ),
        migrations.AddField(
            model_name='user',
            name='saturday_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Закінчення робочого дня в субботу'),
        ),
        migrations.AddField(
            model_name='user',
            name='sunday',
            field=models.BooleanField(default=False, verbose_name='Неділя робочий день?'),
        ),
        migrations.AddField(
            model_name='user',
            name='sunday_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Початок робочого дня в неділю'),
        ),
        migrations.AddField(
            model_name='user',
            name='sunday_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Закінчення робочого дня в неділю'),
        ),
        migrations.AddField(
            model_name='user',
            name='thursday',
            field=models.BooleanField(default=True, verbose_name='Четвер робочий день?'),
        ),
        migrations.AddField(
            model_name='user',
            name='thursday_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Початок робочого дня в четвер'),
        ),
        migrations.AddField(
            model_name='user',
            name='thursday_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Закінчення робочого дня в четвер'),
        ),
        migrations.AddField(
            model_name='user',
            name='tuesday',
            field=models.BooleanField(default=True, verbose_name='Вівторок робочий день?'),
        ),
        migrations.AddField(
            model_name='user',
            name='tuesday_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Початок робочого дня в вівторок'),
        ),
        migrations.AddField(
            model_name='user',
            name='tuesday_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Закінчення робочого дня в вівторок'),
        ),
        migrations.AddField(
            model_name='user',
            name='wednesday',
            field=models.BooleanField(default=True, verbose_name='Середа робочий день?'),
        ),
        migrations.AddField(
            model_name='user',
            name='wednesday_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Початок робочого дня в середу'),
        ),
        migrations.AddField(
            model_name='user',
            name='wednesday_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Закінчення робочого дня в середу'),
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='День')),
                ('time_from', models.DateField(verbose_name='Час від')),
                ('time_to', models.DateField(verbose_name='Час до')),
                ('advocat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Адвокат')),
            ],
            options={
                'verbose_name': 'Робочий день',
                'verbose_name_plural': 'Робочі дні',
            },
        ),
    ]
