# Generated by Django 3.1 on 2020-09-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gao', '0002_auto_20200821_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='time_from',
            field=models.TimeField(verbose_name='Працює з'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='time_to',
            field=models.TimeField(verbose_name='Працює до'),
        ),
    ]
