# Generated by Django 3.1 on 2020-08-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gao', '0002_auto_20200815_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
