# Generated by Django 3.0.2 on 2020-04-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
