# Generated by Django 3.1 on 2020-09-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gao', '0003_auto_20200901_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='test', max_length=150, verbose_name="Повне ім'я"),
            preserve_default=False,
        ),
    ]
