# Generated by Django 3.1 on 2020-09-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gao', '0004_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стать'),
        ),
    ]
