# Generated by Django 3.1 on 2020-09-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gao', '0007_auto_20200903_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='Завершується в'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='Починається в'),
        ),
    ]
