# Generated by Django 3.1 on 2020-09-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gao', '0009_auto_20200903_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='faculty',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Галузь'),
        ),
    ]
