# Generated by Django 3.1 on 2020-09-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gao', '0010_consultation_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='faculty',
        ),
        migrations.AddField(
            model_name='consultation',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='consulations', to='gao.Faculty', verbose_name='Галузі права'),
        ),
    ]
