# Generated by Django 3.1 on 2020-09-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gao', '0011_auto_20200903_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='faculties',
        ),
        migrations.AddField(
            model_name='consultation',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulations', to='gao.faculty', verbose_name='Галузь права'),
        ),
    ]
