# Generated by Django 3.1 on 2020-08-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_consultation_consultationdocument_consultationpayment_faculty'),
        ('custom_auth', '0002_auto_20200815_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ManyToManyField(blank=True, to='app.Faculty', verbose_name='Галузі права'),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.FloatField(default=1, verbose_name='Ціна за годину консультації'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('advocat', 'advocat')], default='client', max_length=255, verbose_name='Роль'),
        ),
    ]
